#!/usr/bin/env python
# -*- encoding: utf-8 -*-
#
# Copyright (C) 2013 Steve Frécinaux
#
# This module is part of hackerfeed and is released under
# the MIT License: http://www.opensource.org/licenses/mit-license.php


import sys

import hackerfeed


hackerfeed.hackerfeed(sys.argv[1], 'cache.db', sys.argv[2])
